Lou8is/docs.nestjs.fr

- content/techniques/caching.md
Please check if your PR fulfills the following requirements:
What kind of change does this PR introduce?
Issue Number: #30
> docs(fr): Translates techniques/caching.md

- content/techniques/mongo.md
Please check if your PR fulfills the following requirements:
What kind of change does this PR introduce?
Issue Number: #35
> docs(fr): Translates techniques/mongo.md

- README.md
- content/techniques/versioning.md
Please check if your PR fulfills the following requirements:
What kind of change does this PR introduce?
Issue Number: #39
> #39 versionning

- .github/PULL_REQUEST_TEMPLATE.md
Please check if your PR fulfills the following requirements:
What kind of change does this PR introduce?
Issue Number: N/A
> docs(fr): Updates PR template to suits this repo needs

- content/techniques/task-scheduling.md
> docs(fr): Translates techniques/task-scheduling.md

- content/techniques/validation.md
- [x ] Traduction d'une nouvelle page
> docs(fr): Translates validation.md

- README.md
- content/techniques/file-upload.md
> docs(fr): Translates techniques/file-upload.md

- content/cli/overview.md
> docs(fr): Translates cli/overview.md

- content/cli/scripts.md
> docs(fr): Translates cli/scripts.md

- content/cli/libraries.md
> docs(fr): Translates cli/libraries.md

- README.md
- content/cli/workspaces.md
> #104 workspaces

- content/devtools/ci-cd.md
- content/devtools/overview.md
> docs(fr): Translates devtools/

- content/websockets/adapter.md
- content/websockets/exception-filters.md
- content/websockets/gateways.md
- content/websockets/guards.md
- content/websockets/interceptors.md
- content/websockets/pipes.md
Issue/PR/Discussion : #81 #82 #83 #84 #85 #86 #87
> #81 websockets

- content/discover/who-uses.json
- content/microservices/nats.md
- content/security/cors.md
- content/techniques/logger.md
> chore(fr): Updates small changes up to EN 900b99d

- content/security/rate-limiting.md
> docs(fr): Updates security/rate-limiting.md to 900b99d

- content/recipes/async-local-storage.md
- content/recipes/automock.md
- content/recipes/cqrs.md
- content/recipes/crud-generator.md
- content/recipes/documentation.md
- content/recipes/hot-reload.md
- content/recipes/mikroorm.md
- content/recipes/mongodb.md
- content/recipes/nest-commander.md
- content/recipes/passport.md
- content/recipes/repl.md
- content/recipes/router-module.md
- content/recipes/serve-static.md
- content/recipes/sql-sequelize.md
- content/recipes/sql-typeorm.md
Issue/PR/Discussion : #117 #118 #119 #120 #122  #123 #124 #125 #126 #127 #133 #130 #132 #135 #136 #134
> #117 recipes

- content/guards.md
> docs(fr): updates content/guards.md to dbf366a

- content/fundamentals/execution-context.md
> chore(fr): Updates small changes up to EN dbf366a

- content/pipes.md
- content/techniques/configuration.md
- content/techniques/cookies.md
- content/techniques/task-scheduling.md
#165 
#167 
#168 
#169 
Ce Pull-Request fixe 4 issues tous liés à la version anglaise `EN-dbf366a`
> chore(fr): update small changes to match EN-dbf366a

- content/techniques/compression.md
- content/techniques/events.md
> Bump to en 900b99d

- content/microservices/basics.md
- content/microservices/custom-transport.md
- content/microservices/exception-filters.md
- content/microservices/grpc.md
- content/microservices/guards.md
- content/microservices/interceptors.md
- content/microservices/kafka.md
- content/microservices/mqtt.md
- content/microservices/nats.md
- content/microservices/pipes.md
- content/microservices/rabbitmq.md
- content/microservices/redis.md
> Translates 88-microservices

- content/fundamentals/unit-testing.md
> docs(fr): updates fundamentals/unit-testing.md to 6a373ad

- content/fundamentals/provider-scopes.md
- content/openapi/operations.md
- content/pipes.md
- content/recipes/terminus.md
- content/techniques/performance.md
> docs(fr): Updates files up to EN-fbc947d

- content/devtools/ci-cd.md
- content/discover/who-uses.json
- content/fundamentals/lazy-loading-modules.md
- content/introduction.md
- content/microservices/basics.md
- content/modules.md
> Update to EN a68b7c8

- content/discover/who-uses.json
- content/exception-filters.md
- content/fundamentals/provider-scopes.md
- content/microservices/grpc.md
- content/microservices/kafka.md
- content/openapi/cli-plugin.md
- content/openapi/introduction.md
- content/recipes/terminus.md
- content/techniques/configuration.md
- content/techniques/file-upload.md
- content/techniques/task-scheduling.md
> docs(fr): Updates several files up to EN-d196fed

- content/recipes/swc.md
> docs(fr): Translates recipes/swc.md

- content/recipes/terminus.md
> docs(fr): Translates recipes/terminus.md

- content/recipes/prisma.md
> docs(fr): Translates recipes/prisma.md

- content/recipes/automock.md
> docs(fr): updates recipes/automock.md to 6a373ad

- content/recipes/mikroorm.md
> docs(fr): updates recipes/mikroorm.md to d196fed

- content/exception-filters.md
- content/interceptors.md
- content/microservices/custom-transport.md
- content/microservices/rabbitmq.md
- content/modules.md
- content/recipes/async-local-storage.md
- content/techniques/logger.md
> docs(fr): updates all files to 761c06c

- content/fundamentals/execution-context.md
- src/app/common/social-wrapper/social-wrapper.component.html
- src/app/common/social-wrapper/social-wrapper.component.scss
- src/app/homepage/header/header.component.html
- src/app/shared/components/theme-mode-toggle/theme-mode-toggle.component.scss
- src/app/shared/components/theme-mode-toggle/theme-mode-toggle.component.ts
> docs(fr): updates to fd1d769

- content/discover/who-uses.json
- content/fundamentals/dependency-injection.md
- content/fundamentals/execution-context.md
- content/fundamentals/unit-testing.md
- content/graphql/subscriptions.md
- content/openapi/introduction.md
- content/security/rate-limiting.md
- src/app/common/social-wrapper/social-wrapper.component.html
- src/app/common/social-wrapper/social-wrapper.component.scss
- src/app/homepage/header/header.component.html
- src/app/shared/components/theme-mode-toggle/theme-mode-toggle.component.scss
- src/app/shared/components/theme-mode-toggle/theme-mode-toggle.component.ts
> Update to fd1d769

- content/techniques/queues.md
> docs(fr): translates queues up to 3438194

- content/techniques/mongo.md
> docs(fr): translates mongo up to c07269
